### ISSUE TITLE
Make contrib/groups/* safer and more well-documented

### ISSUE THREAD

**Issue by sshine** [DIKU-EDU/staffeli#34]
- [x] The [documentation for contrib/groups/create-groups.py](https://github.com/DIKU-EDU/staffeli/tree/master/contrib/groups#step-3-groups) isn't accurate wrt. number of arguments.
- [x] check-groups.py should assert that the group.txts it finds are actually plaintext files and not RTF documents or pictures of kittens.
- [ ] create-groups.py fails when two individuals both upload a group.txt that put them in the same group:

        (staffeli) ~/Courses/ap17/ap-e2017-grading $ create-groups.py subs/1/ 'Assignment 1 Groups' subs/1/groups.txt    
        Traceback (most recent call last):
          File "/home/simon/Courses/ap17/staffeli/contrib/groups/create-groups.py", line 62, in <module>
            sys.exit(create(*sys.argv[1:]))
          File "/home/simon/Courses/ap17/staffeli/contrib/groups/create-groups.py", line 51, in create
            assert len(subpaths) == 1
        AssertionError

    Either the documentation should be clear about what to when check-groups.py fails in various ways, or the script should handle the situation gracefully, e.g. by detecting that groups (abc123 def456) and (def456 abc123) are the same and only create one group for them.

- [ ] It would be neat if the script had a "dry run" parameter that doesn't create groups but fetches the ones that are created and performs the filesystem operations with them. Currently this isn't possible because [`canvas.create_group()`](https://github.com/DIKU-EDU/staffeli/blob/master/staffeli/canvas.py#L465) (used [here](https://github.com/DIKU-EDU/staffeli/blob/master/contrib/groups/create-groups.py#L38)) both creates a group on Canvas and returns the group's properties. If there were a `canvas.get_groups()`, that'd be neat.

**Comment by sshine** [comment]
Actually, these tools should probably be polished and re-incorporated into the `staffeli` tool.

Why not, @oleks and @nqpz?

**Comment by sshine** [comment]
See comments for previous commit. `create-groups.py` should work again for [this tutorial](https://github.com/DIKU-EDU/staffeli/tree/master/contrib/groups). I'll improve further on it in my attempt to make it a part of the `staffeli` tool, which is currently my third-priority.
